# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 297dfd9b18f6ba75207efa5443549d3d9248b94415b2f8eae92ca5a888ea3f57064759ab778f450528cfce60750ef64c6b498561d3ad46fa1200c74dc44395d1

test:
  secret_key_base: 54ee8c7be281281952e303cc6f9ca7dcbf229797d49a2cbdec65fe5e92455a34b5554b27a5b981631ccf0356ee176a0745ee6790e8af3ad165c0641a8103363a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
